@version: 4.8
@include "scl.conf"

options {
    chain_hostnames(off);
    use_dns(no);
    keep_hostname(yes);
    flush_lines(1);
};

source s_tls {
    network(
        ip(0.0.0.0)
        port(6514)
        transport("tls")
        tls(
            key-file("/etc/syslog-ng/certs/server.key")
            cert-file("/etc/syslog-ng/certs/server.pem")
            ca-file("/etc/syslog-ng/certs/ca.pem")
            peer-verify(optional-untrusted)
        )
    );
};

destination d_eos {
    file("/var/log/syslog/eos.log" template("$ISODATE $HOST $MSGHDR$MSG\n"));
};

log {
    source(s_tls);
    destination(d_eos);
};
